"""Add reference number to Booking model

Revision ID: 36f2c88c00a7
Revises: ddeef9eb27d9
Create Date: 2024-09-09 12:54:08.211343

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36f2c88c00a7'
down_revision = 'ddeef9eb27d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reference_number', sa.String(length=8), nullable=False))
        batch_op.create_unique_constraint('uq_booking_reference_number', ['reference_number'])
        # Add a named constraint for the reference_number column
        batch_op.create_index('ix_booking_reference_number', ['reference_number'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        # Remove the named constraint for the reference_number column
        batch_op.drop_index('ix_booking_reference_number')
        batch_op.drop_constraint('uq_booking_reference_number', type_='unique')
        batch_op.drop_column('reference_number')

    # ### end Alembic commands ###
