"""empty message

Revision ID: d86dfb468d52
Revises: e78783ab451c
Create Date: 2024-09-09 13:12:03.844661

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd86dfb468d52'
down_revision = 'e78783ab451c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.alter_column('reference_number',
               existing_type=sa.VARCHAR(length=8),
               type_=sa.String(length=13),
               nullable=False)
        batch_op.alter_column('booking_date',
               existing_type=sa.DATE(),
               type_=sa.String(length=10),
               nullable=True)
        batch_op.alter_column('training_date',
               existing_type=sa.DATE(),
               type_=sa.String(length=10),
               nullable=True)
        batch_op.create_unique_constraint(None, ['reference_number'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('training_date',
               existing_type=sa.String(length=10),
               type_=sa.DATE(),
               nullable=False)
        batch_op.alter_column('booking_date',
               existing_type=sa.String(length=10),
               type_=sa.DATE(),
               nullable=False)
        batch_op.alter_column('reference_number',
               existing_type=sa.String(length=13),
               type_=sa.VARCHAR(length=8),
               nullable=True)

    # ### end Alembic commands ###
