"""Add reference number to Booking model

Revision ID: ddeef9eb27d9
Revises: 24952d6ea855
Create Date: 2024-09-09 12:51:47.619924

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ddeef9eb27d9'
down_revision = '24952d6ea855'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reference_number', sa.String(length=8), nullable=False))
        batch_op.create_unique_constraint('uq_booking_reference_number', ['reference_number'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('training_date',
               existing_type=sa.String(length=10),
               type_=sa.DATE(),
               nullable=False)
        batch_op.alter_column('booking_date',
               existing_type=sa.String(length=10),
               type_=sa.DATE(),
               nullable=False)
        batch_op.drop_column('reference_number')

    # ### end Alembic commands ###
