"""empty message

Revision ID: e78783ab451c
Revises: e329b515c19f
Create Date: 2024-09-09 13:09:14.805185

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e78783ab451c'
down_revision = 'e329b515c19f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_booking')
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.alter_column('reference_number',
               existing_type=sa.VARCHAR(length=8),
               type_=sa.String(length=13),
               nullable=False)
        batch_op.alter_column('booking_date',
               existing_type=sa.DATE(),
               type_=sa.String(length=10),
               nullable=True)
        batch_op.alter_column('training_date',
               existing_type=sa.DATE(),
               type_=sa.String(length=10),
               nullable=True)
        batch_op.create_unique_constraint(None, ['reference_number'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('training_date',
               existing_type=sa.String(length=10),
               type_=sa.DATE(),
               nullable=False)
        batch_op.alter_column('booking_date',
               existing_type=sa.String(length=10),
               type_=sa.DATE(),
               nullable=False)
        batch_op.alter_column('reference_number',
               existing_type=sa.String(length=13),
               type_=sa.VARCHAR(length=8),
               nullable=True)

    op.create_table('_alembic_tmp_booking',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('client_name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('email', sa.VARCHAR(length=120), nullable=False),
    sa.Column('mobile_number', sa.VARCHAR(length=20), nullable=False),
    sa.Column('booking_date', sa.DATE(), nullable=False),
    sa.Column('training_date', sa.DATE(), nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), nullable=False),
    sa.Column('attachment_filename', sa.VARCHAR(length=255), nullable=True),
    sa.Column('address', sa.VARCHAR(length=255), nullable=True),
    sa.Column('organization_name', sa.VARCHAR(length=100), nullable=True),
    sa.Column('reference_number', sa.VARCHAR(length=8), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reference_number', name='uq_booking_reference_number')
    )
    # ### end Alembic commands ###
